export const clothingTypeList: string[] = [
    'shirt',
    'shirts',
    'T-shirt',
    'T-shirts',
    'Chemise',
    'Chemises',
    'Chemisier',
    'Chemisiers',
    'Doudoune',
    'Puffy jacket',
    'Pull',
    'Pulls',
    'Sweat à capuche',
    'Sweats à capuche',
    'Veste',
    'Vestes',
    'Manteau',
    'Manteaux',
    'Pantalon',
    'Pantalons',
    'Jean',
    'Jeans',
    'Jupe',
    'Jupes',
    'Robe',
    'Robes',
    'Costume',
    'Costumes',
    'Chaussure',
    'Chaussures',
    'Blazer',
    'Blazers',
    'Survêtement',
    'Survêtements',
    'Short',
    'Shorts',
    'Legging',
    'Leggings',
    'Combinaison',
    'Combinaisons',
    'Maillot de bain',
    'Maillots de bain',
    'Pyjama',
    'Pyjamas',
    'Sous-vêtement',
    'Sous-vêtements',
  ];